#Basic

In [2]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [4]:
print("hello")

hello


In [12]:
a = 4
b = 6
print('a = '+str(a) + ' & b = '+str(b))

a = 4 & b = 6


In [14]:
type(a)

int

In [16]:
s1 = "RJ College"
type(s1)

str

In [18]:
pi = 3.145
type(pi)

float

#Markdown Guide Practice

##Equations
$y = x^2$

---

$e^{i\pi} + 1 = 0$

---
$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

---
 
$\frac{n!}{k!(n-k)!} = {n \choose k}$

---
 
$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

---





#NumPy
https://numpy.org/doc/stable/user/whatisnumpy.html

In [23]:
a = [1,2,3]
a

[1, 2, 3]

In [25]:
type(a)

list

In [28]:
b = [4,5,6]
b

[4, 5, 6]

In [38]:
#Multiplication
c = []
for i in range(len(a)):
  c.append(a[i]*b[i])
c

[4, 10, 18]

In [37]:
#Addition of two array
c = []
for i in range(len(a)):
  c.append(a[i]+b[i])
c

[5, 7, 9]

In [40]:
import time
print("Sleeping")
time.sleep(30) # sleep for a while; interrupt me!
print("Done Sleeping")

Sleeping
Done Sleeping


In [ ]:
import numpy as np


In [45]:
#define automatic array
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
a.ndim

2

In [49]:
a.dtype

dtype('int64')

In [51]:
a.dtype.name

'int64'

In [53]:
#itemsize = row + column
a.itemsize

8

In [55]:
#size = total no. of elements in the array
a.size

15

In [56]:
type(a)

numpy.ndarray

In [58]:
#define array manually
b = np.array([[12,13,14],[15,16,17]])
b

array([[12, 13, 14],
       [15, 16, 17]])

In [61]:
#reshape the manual array using 'reshape'

c = b.reshape(3,2)
c

array([[12, 13],
       [14, 15],
       [16, 17]])

In [68]:
#Create an array of 10 characters with 2 rows and 5 columns
d = np.array(['p','a','v','a','n','y','a','d','a','v'])
s = d.reshape(2,5)
s

array([['p', 'a', 'v', 'a', 'n'],
       ['y', 'a', 'd', 'a', 'v']], dtype='<U1')