#**Array**

In [ ]:
import numpy
numpy.__version__

'1.19.5'

In [ ]:
list1 = []
list1

[]

In [ ]:
type(list1)

list

In [ ]:
list2 = list(range(5))
list2

[0, 1, 2, 3, 4]

In [ ]:
list3 = [str(c) for c in list2]
list3

['0', '1', '2', '3', '4']

In [ ]:
list4 = [1,20.1,'u','Bharat',True]
list4

[1, 20.1, 'u', 'Bharat', True]

In [ ]:
type(list4)

list

In [ ]:
#To checkout the type of each element present in the array list
[type(item) for item in list4]

[int, float, str, str, bool]

In [ ]:
#Python array
import array as ar
L = list(range(5))
A = ar.array('i',L)   # i indicate that's the contains are integers
A

array('i', [0, 1, 2, 3, 4])

In [ ]:
#NumPy array
import numpy as np
#integer array
np.array([1,5,3,8,4])

array([1, 5, 3, 8, 4])

In [ ]:
#Automatic/Implicit conversion of values/elements
np.array([10.1,2,8,4,5])

array([10.1,  2. ,  8. ,  4. ,  5. ])

In [ ]:
#Explicit conversion of values/elements
np.array([1,2,5,4,3], dtype = 'float32')

array([1., 2., 5., 4., 3.], dtype=float32)

In [ ]:
#[[,,],[,,],[,,]]
#nested list result in multi-dimensional array
np.array([range(i,i+3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Create a length in integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Create array of zero of float type
np.zeros((2,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Create array of one of float type
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
 
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 3
# (this is similar to the built-in range() function)
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
#0 to 2   4 element   
#Creation of an array of evenly spaced values for the given range
#0 is starting, 1 is destination and 3 is steps/elements
np.linspace(0, 1, 3)


array([0. , 0.5, 1. ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.62419304, 0.58271561, 0.45689413],
       [0.90701878, 0.86458051, 0.95704277],
       [0.49361389, 0.04904076, 0.2635183 ]])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (2, 3))  # 0 is mean 1 is SD and 2,3 is dimension(row & column following)

array([[-0.34138708, -0.94008032,  0.27539355],
       [-0.12555606, -0.03480162,  0.21427783]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3)) # 0 is starting 10 is ending but not include and last one is 3,3 is dimension(rows and columns )

array([[1, 7, 2],
       [3, 7, 3],
       [9, 0, 1]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

#**Numpy**

In [ ]:
import numpy as np
np.random.seed(20)  # seed for reproducibility
x1 = np.random.randint(20, size=10)  # One-dimensional array
x1

array([ 3, 15,  9, 11,  7,  2,  0,  8, 19, 16])

In [ ]:
#Seed 100 value can go upto 200 and create a array as 5,6,7(3x3 dimension)
np.random.seed(100)
x2 = np.random.randint(200, size=(5,6,7)) #->5 is SETs, ->6 is ROWs & ->7 is COLUMNs
x2


array([[[  8,  24,  67, 103,  87,  79, 176],
        [138,  94, 180,  98,  53,  66,  14],
        [ 34,  24, 143, 107,  60,  58, 144],
        [137,  93,  86, 130, 155, 108, 132],
        [159, 129, 141, 100,   4,  91, 187],
        [ 67, 135,  49, 175, 193,  61,  14]],

       [[183, 199,  80,   2, 121, 105, 147],
        [ 63, 181,  27,  56, 113, 158, 176],
        [ 47, 167, 109,  38, 172,  18, 192],
        [184, 162, 181,  17,  72,  13, 106],
        [ 30,  17,  53,  68, 178,  91, 181],
        [ 78,   0,  13, 185, 106, 131,  70]],

       [[131, 138, 188, 131, 105, 176, 180],
        [ 43,  36,   5,  71,  38,  94, 170],
        [ 84,  95, 114, 119,  76,  33,  58],
        [102, 170, 150,   0, 183, 147,  53],
        [196, 190,  50, 196, 163, 151,   9],
        [176,  21, 153, 182,   6, 165, 102]],

       [[122, 116, 186,  39, 107,  51,  30],
        [121,  66, 152, 183,  17,  45,  89],
        [173,  35,  16,  12,  86, 109,  67],
        [ 20, 138,   8, 158, 140, 146,  93],
    

In [ ]:
#Seed 100 value can go upto 200 and create a array as 5,6,7(3x3 dimension)
np.random.seed(100)
x2 = np.random.randint(200, size=(5,2,2)) #->5 is SETs, ->2 is ROWs & ->2 is COLUMNs
x2


array([[[  8,  24],
        [ 67, 103]],

       [[ 87,  79],
        [176, 138]],

       [[ 94, 180],
        [ 98,  53]],

       [[ 66,  14],
        [ 34,  24]],

       [[143, 107],
        [ 60,  58]]])

In [ ]:
np.random.seed(100)
x2 = np.random.randint(200, size=(4,2,2,2)) #->4 is repeted,->2 is SETs, means =>> 4 * 2 = 8 ->6 is ROWs & ->7 is COLUMNs (4x4 dimension)
x2


array([[[[  8,  24],
         [ 67, 103]],

        [[ 87,  79],
         [176, 138]]],


       [[[ 94, 180],
         [ 98,  53]],

        [[ 66,  14],
         [ 34,  24]]],


       [[[143, 107],
         [ 60,  58]],

        [[144, 137],
         [ 93,  86]]],


       [[[130, 155],
         [108, 132]],

        [[159, 129],
         [141, 100]]]])

In [ ]:
# 5 dimensions 3x4x3x2x2
np.random.seed(100)
x2 = np.random.randint(200, size=(3,4,3,2,2)) #->3 times is repeted,->2 is SETs, means =>> 4 * 2 = 8 ->6 is ROWs & ->7 is COLUMNs (4x4 dimension)
x2


array([[[[[  8,  24],
          [ 67, 103]],

         [[ 87,  79],
          [176, 138]],

         [[ 94, 180],
          [ 98,  53]]],


        [[[ 66,  14],
          [ 34,  24]],

         [[143, 107],
          [ 60,  58]],

         [[144, 137],
          [ 93,  86]]],


        [[[130, 155],
          [108, 132]],

         [[159, 129],
          [141, 100]],

         [[  4,  91],
          [187,  67]]],


        [[[135,  49],
          [175, 193]],

         [[ 61,  14],
          [183, 199]],

         [[ 80,   2],
          [121, 105]]]],



       [[[[147,  63],
          [181,  27]],

         [[ 56, 113],
          [158, 176]],

         [[ 47, 167],
          [109,  38]]],


        [[[172,  18],
          [192, 184]],

         [[162, 181],
          [ 17,  72]],

         [[ 13, 106],
          [ 30,  17]]],


        [[[ 53,  68],
          [178,  91]],

         [[181,  78],
          [  0,  13]],

         [[185, 106],
          [131,  70]]],


        [[[131, 13

In [ ]:
x2.shape

(3, 4, 3, 2, 2)

In [ ]:
x2.ndim

5

In [ ]:
x2.size

144

In [ ]:
x2.nbytes

1152

In [ ]:
x2.itemsize

8